spring.application.name=docucloud-backend

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3307/docucloud?createDatabaseIfNotExist=true}
spring.datasource.username=root
spring.datasource.password=manuela14012
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.error.include-message=always

security.jwt.secret=${JWT_SECRET:DocuCloudSuperSecretKeyForDevOnlyChangeInProduction12345}
security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:180}

storage.base-path=${STORAGE_BASE_PATH:./storage}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
